# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReservaVuelos', '0002_auto_20160805_1358'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registro',
        ),
    ]
