# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservaVuelos', '0003_delete_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=200)),
                ('destino', models.CharField(max_length=200)),
                ('partida', models.DateField()),
                ('regreso', models.DateField()),
                ('clase', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=20)),
                ('adulto', models.IntegerField()),
                ('ninio', models.IntegerField()),
                ('bebe', models.IntegerField()),
                ('tarifa', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
